### ISSUE TITLE
amiyabot服务密钥为空或纯数字时的安装问题

### ISSUE THREAD

**Issue by niechy** [hsyhhssyy/amiyabot-arknights-hsyhhssyy-maa#4]
当amiyabot未设置服务密钥时
maa对接器会安装失败，NoneType
```
2023-08-07 11:21:59,428
Main
ERROR
plugin install error: Traceback (most recent call last): 
  File "C:\Users\NCY\Desktop\Amiya-Bot\lib\site-packages\amiyabot\log\manager.py", line 133, in sync_catch 
    yield 
  File "C:\Users\NCY\Desktop\Amiya-Bot\lib\site-packages\amiyabot\factory\__init__.py", line 240, in install_plugin 
    instance.install() 
  File "C:\Users\NCY\Desktop\Amiya-Bot\plugins\amiyabot-arknights-hsyhhssyy-maa-1_0\main.py", line 35, in install 
    if not is_strong_password(): 
  File "C:\Users\NCY\Desktop\Amiya-Bot\plugins\amiyabot-arknights-hsyhhssyy-maa-1_0\server\check_password.py", line 11, in is_strong_password 
    if len(password) < 8: 
TypeError: object of type 'NoneType' has no len() 
```
并且若服务密钥为纯数字时，为int类型，无法使用len()
```
2023-08-07 11:23:29,214
Main
ERROR
plugin install error: Traceback (most recent call last): 
  File "C:\Users\NCY\Desktop\Amiya-Bot\lib\site-packages\amiyabot\log\manager.py", line 133, in sync_catch 
    yield 
  File "C:\Users\NCY\Desktop\Amiya-Bot\lib\site-packages\amiyabot\factory\__init__.py", line 240, in install_plugin 
    instance.install() 
  File "C:\Users\NCY\Desktop\Amiya-Bot\plugins\amiyabot-arknights-hsyhhssyy-maa-1_0\main.py", line 35, in install 
    if not is_strong_password(): 
  File "C:\Users\NCY\Desktop\Amiya-Bot\plugins\amiyabot-arknights-hsyhhssyy-maa-1_0\server\check_password.py", line 11, in is_strong_password 
    if len(password) < 8: 
TypeError: object of type 'int' has no len() 
```

#2 很有可能是一样的问题

**Comment by hsyhhssyy** [comment]
下一版我这里改一下，输出一个更加友好的错误信息。

**Comment by hsyhhssyy** [comment]
提交了一个新版，再试一下看看还会不会直接报错
现在应该是可以安装但是不能使用了

**Comment by niechy** [comment]
刚刚测过了，没有密码也可以正常安装
